[FEAT] [SETTING] Building Database and Update build.gradle
euphony-io/order-with pull request #6
Opened 2022-07-25 07:58 UTC by phj0407

Building database (data folder - dto, dao) 
Add explanation in build.gradle for using aar file

2022-07-25 09:38 UTC, SeonJK reviewed
리뷰입니다! 제가 혹시 이해하지 못하고 코멘트 남긴 부분은 설명해주시면 감사하겠습니다 :)

2022-07-25 09:38 UTC, SeonJK commented on app/build.gradle
>      // Euphony
euphony의 `PREREQUISITE.md`에 있는 순서대로 작성하는게 어떨까요?

```groovy
// 1. Just implement library
def euphony_version = "0.7.1.6"
implementation "co.jbear.lib:euphony:$euphony version"

/** 2. Here is another way to implement euphony by importing aar/jar file directory.
  * https://search.maven.org/artifact/co.jbear.lib/euphony/0.7.1.6/aar
  * Please read `PREREQUISITE.md` for more details in euphony */
implementation files('libs/euphony_0.7.1.6.aar')
```

이렇게 생각해봤습니다!

2022-07-25 09:38 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/AppDatabase.kt
> +@Database(entities = [ Order::class, Menu::class, OrderMenu::class], version = 3)
database version이 3인 이유가 있을까요?

2022-07-25 09:38 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +    // 1-3. Get menu by name
혹시 name과 title이 같은 데이터인가요? 이름의 통일이 필요할 것 같습니다!

2022-07-25 09:38 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +    // 1-1. Get all menu (id, title, description, cost)
주석에 image도 추가 부탁드립니다!

2022-07-25 09:38 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
> +    fun delete(menus: Menu)
제가 알기로는 @Delete 어노테이션을 쓰면 한 아이템을 지우는 것으로 알고 있습니다.
파라미터 이름을 복수가 아니라 `menu`나 `menuItem`처럼 단수로 정하면 좋을 것 같아요~

2022-07-25 09:38 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/dto/Menu.kt
> +    @ColumnInfo(name = "image") val image: String?,
image의 자료형은 Url?이 되어야할 것 같아요!

2022-07-25 09:38 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/dto/OrderMenu.kt
> +data class OrderMenu (
id의 역할이 무엇인지 여쭤봐도 될까요? 만약 유니크키를 위한 것이라면,
제가 DB에 대해 잘 모르긴 하는데 관계DB?일 경우에 별도 id를 두지 않고 두 FK를 PK로 지정해도 유니크한 키가 될 것 같아 건의드립니다!

2022-07-25 09:41 UTC, SeonJK requested changes
/.idea/deploymentTargetDropDown.xml과 /.idea/gradle.xml은 삭제 부탁드립니다!
/.idea/gradle.xml의 경우엔 gradle관련 로컬경로가 들어있는데 사용자마다 달라집니다.
/.idea/deploymentTargetDropDown.xml은 처음보는 친구네요...

/.idea 파일들이 왜 안걸러지는지 이해를 못하겠어요ㅠㅠㅠㅠ

2022-07-25 11:34 UTC, yeonns commented
@SeonJK gitignore에 포함시킨 파일이더라도, 적용이 안되는 경우가 간혹 있습니다 ㅎㅎ
그럴 땐 아래와 같이 git rm 후에 gitignore가 적용된 파일들을 전부 모아 commit하면 됩니다!
Reference: https://nesoy.github.io/articles/2017-01/Git-Ignore
```
$ git rm -r --cached
$ git add .
$ git commit -m "reapply gitignore"
$ git push origin master
# PR 만드시면 됩니다
```

2022-07-25 12:07 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/AppDatabase.kt
> +@Database(entities = [ Order::class, Menu::class, OrderMenu::class], version = 3)
제가 테스트 돌리다가 3까지 올라가버려서 그렇습니다... 1로 수정했습니다!

2022-07-25 12:07 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +    // 1-1. Get all menu (id, title, description, cost)
네, 수정하겠습니다!

2022-07-25 12:07 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +    // 1-3. Get menu by name
name으로 통일했습니다!

2022-07-25 12:07 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
> +    fun delete(menus: Menu)
맞습니다, 한 아이템만 지우는 건데 혼란의 여지가 있었네요! menu로 수정하겠습니다!

2022-07-25 12:07 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dto/Menu.kt
> +    @ColumnInfo(name = "image") val image: String?,
네, 수정하겠습니다!

2022-07-25 12:18 UTC, phj0407 commented on app/build.gradle
>      // Euphony
더 짜임새있는 구조가 될 것 같네요! 반영하겠습니다.

2022-07-25 12:23 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/AppDatabase.kt
> +@Database(entities = [ Order::class, Menu::class, OrderMenu::class], version = 3)
엇 그럼 혜진님 프로젝트에서 1로 수정해도 잘 되시나요?

2022-07-25 12:26 UTC, SeonJK reviewed
아직 title로 남아있는 곳이 있어서 name으로 변경 요청드립니다!

2022-07-25 12:26 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +    fun addMenu(title: String, description: String, image: URL , cost: Int) {
이부분도 name으로 변경 부탁드립니다 :)

2022-07-25 12:26 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/dto/Menu.kt
> +    @ColumnInfo(name = "image") val image: String?,
아 이부분은 저희 오늘 스프린트때 이야기 해보는게 좋을 것 같습니다!

2022-07-25 12:27 UTC, SeonJK commented
> @SeonJK gitignore에 포함시킨 파일이더라도, 적용이 안되는 경우가 간혹 있습니다 ㅎㅎ 그럴 땐 아래와 같이 git rm 후에 gitignore가 적용된 파일들을 전부 모아 commit하면 됩니다! Reference: https://nesoy.github.io/articles/2017-01/Git-Ignore
> 
> ```
> $ git rm -r --cached
> $ git add .
> $ git commit -m "reapply gitignore"
> $ git push origin master
> # PR 만드시면 됩니다
> ```

감사합니다 멘토님!! 참고해서 적용해보겠습니다 :)

2022-07-25 12:57 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dto/OrderMenu.kt
> +data class OrderMenu (
PK의 역할입니다! 대표 id를 PK로 두는 방법과 복합키를 PK 로 두는 방법 모두 하나의 필드가 필요한데, 혹시 복합키를 사용할 이유가 따로 있으실까요? ?

2022-07-25 12:58 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +    fun addMenu(title: String, description: String, image: URL , cost: Int) {
놓치는 부분이 많네요... 알려주셔서 감사합니다!

2022-07-25 13:27 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/OrderDao.kt
> +    fun insertAll(vararg order: Order)
보통 insert를 할 때는 리스트를 인자로 많이 넣게 되는데 vararg로 하신 이유가 있을까요?

2022-07-25 13:32 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/OrderDao.kt
> +    fun insertAll(vararg order: Order)
insert 할 때는 onConflict를 사용해서 겹쳤을 때를 대비해야해요! 디폴트값은 abort인데 OnConflictStrategy.REPLACE를 사용해서 교체되도록 하면 어떨까요?

2022-07-25 13:38 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/OrderDao.kt
> +    fun insertAll(vararg order: Order)
유동적으로 받으려고 vararg로 했습니다~ List로 하면 1개 넣어도 List 생성해야 하는데 이렇게 하면 생성 없이 나열해서 여러개 넣을 수 있어서요!

2022-07-25 13:39 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
> +    fun insertAll(vararg menus: Menu) : List<Long>
insert에서 반환값을 설정하신 이유는 뭔가요??

2022-07-25 13:42 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +        ).allowMainThreadQueries().build()
<img width="829" alt="스크린샷 2022-07-25 오후 10 41 41" src="https://user-images.githubusercontent.com/67946662/180791403-4fa853c2-38ac-41d1-a8c1-067495869d52.png">

allowMainThreadQueries() 빼는게 좋을 것 같습니다!

2022-07-25 13:48 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +        var isSuccess = false
이 부분 DAO에서 deleteById로 SQL문으로 지우는게 나을 것 같아요! 지금은 DB를 두 번 접근하고 있어서 작업량이 너무 커질 수 있어용

2022-07-25 13:48 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +        if (order != null) {
이 부분도요!

2022-07-25 13:51 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/OrderMenuDao.kt
> +    @Query("Select om.id as id, om.order_id as orderId, menu.name as menuName, om.count as count from OrderMenu om Left join menu on om.menu_id = menu.id")
SQL 문법 (ex : SELECT, Select), 띄어쓰기 통일시키면 좋을 것 같아요!

2022-07-25 13:56 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
> +    fun insertAll(vararg menus: Menu) : List<Long>
rowId 확인을 위한 반환 값입니다.

2022-07-25 13:58 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/OrderDao.kt
> +    fun insertAll(vararg order: Order)
id가 고유 식별 값이니 id를 validation하는 방향이 더 좋지 않을까요? REPLACE로 하면 잘못된 데이터여도 그대로 교체될거니까 오히려 저희가 검증을 놓칠 수 있다고 생각해요. ㅎㅎ 아니면 이 부분은 저희끼리 규칙을 정하고 그에 따라 진행하면 좋을 것 같습니다~~

2022-07-25 13:59 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +        ).allowMainThreadQueries().build()
우선 메인 스레드에서 DB 동작 먼저 확인했습니다. 이 부분은 다음 커밋에 반영할 예정입니다!

2022-07-25 14:59 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/dto/OrderMenu.kt
> +data class OrderMenu (
하나의 필드가 필요하다는 뜻을 이해하지 못했는데 설명 부탁드립니다!
제가 복합키로 PK를 제안한건 현재 엔티티 안에 이미 FK로 두 엔티티의 PK를 가져온 상태라 별도 id를 만들지 않아도 될 것 같아서 말씀드렸습니다~!

2022-07-25 15:26 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/AppDatabase.kt
> +@Database(entities = [ Order::class, Menu::class, OrderMenu::class], version = 3)
아뇨 제 프로젝트에서는 이미 수정(변화) 기록이 있어서 안 됩니다~ 처음 받아서 쓸 떄는 변경사항이 없을테니 1로 해도 돼요!

2022-07-25 15:29 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dto/OrderMenu.kt
> +data class OrderMenu (
https://hoon93.tistory.com/m/57

요 글에 설명이 잘 돼있네요ㅎㅎ
하나의 필드가 필요하다는 건 어차피 {PK, PK} 로 칼럼으로 구성된 키를 만들고 다시 넣어줘야한다는 뜻이었어요!

2022-07-25 15:34 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
> +    fun insertAll(vararg menus: Menu) : List<Long>
테스트 할 때 insert 가 잘 됐는지 확인 용으로 사용했습니다. 제가 dbUtil 에 메서드에서 사용하지 않았을 뿐이지 lasti nsert id 등등 데이터 확인 시 사용하는 경우가 있을 것 같습니다.

2022-07-25 15:37 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
> +    fun insertAll(vararg menus: Menu) : List<Long>
엇.. 테스트용으로 사용된건 지우고 피알 올려주시면 좋을 것 같습니다!

2022-07-25 15:41 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +        var isSuccess = false
두 번 접근하는 게 
1. id로 메뉴 찾기
2. 메뉴 삭제

를 말씀하시는 걸까요? 1번은 존재하지 않는 메뉴 delete 시도하는 상황을 고려해서 넣은 부분입니다! 제가 테스트 할 때 걸린 부분이라서요. 이 부분 확인을 고려한다면 두 번 접근 외에 좋은 방법이 안 떠오르네요.... 혹시 작업량에 큰 문제가 생길까요?

2022-07-25 15:53 UTC, serim53 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +        var isSuccess = false
> 를 말씀하시는 걸까요? 1번은 존재하지 않는 메뉴 delete 시도하는 상황을 고려해서 넣은 부분입니다! 제가 테스트 할 때 걸린 부분이라서요. 이 부분 확인을 고려한다면 두 번 접근 외에 좋은 방법이 안 떠오르네요.... 혹시 작업량에 큰 문제가 생길까요?

아 작업량이 메인 스레드에서 관여하는 작업이 많아진다는 뜻이었어요! 말씀드린 개선 방향은 현재는 findById(), 
delete()를 통해서 db에 두번 접근하고 있는데, 이걸 DAO에서 아예 deleteById()를 만들어서 쿼리문으로 한번에 처리해주는게 좋을 것 같다는 생각이었습니다!

2022-07-25 16:38 UTC, SeonJK commented on app/src/main/java/com/euphonyio/orderwith/data/dto/OrderMenu.kt
> +data class OrderMenu (
주신 링크 잘 보았습니다!
링크대로 하면 {PK, PK}로 구성된 칼럼을 하나 더 만들기보다 id값 없이 기본키를 복수로 지정할 수 있을 것 같습니다!

```kotlin
@Entity(
    primaryKeys = {"order_id", "menu_id"},
    ...
)
data class OrderMenu (
    @NonNull @ColumnInfo(name="order_id") val order_id: Int,
    @NonNull @ColumnInfo(name="menu_id") val menu_id: Int,
    @ColumnInfo(name="count") val count: Int
)
```

2022-07-26 14:43 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
> +    fun insertAll(vararg menus: Menu) : List<Long>
앗 그럼 추후 데이터 조회하는 경우는 일단 배제한다고 생각하면 될까요...?  PK id가 있긴 하지만 안전성을 위해 rowid 를 반환하는 부분을 남겨두는 것도 좋을 것 같습니다!

2022-07-26 14:43 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
> +        var isSuccess = false
findById() 는 존재하는 메뉴인지 확인하는 목적으로 실행됩니다. 곧바로 deleteById() 만 실행한다면 없는 메뉴 id를 입력해도 작업 성공 여부를 알 수 없는 경우가 생기더라구요. 이 부분 고려하지 않아도 괜찮을까요?

2022-07-26 14:43 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
> +    fun insertAll(vararg menus: Menu) : List<Long>
https://www.devkuma.com/docs/sqlite/rowid-%EC%B0%B8%EC%A1%B0-%EB%B0%8F-integer-primary-key%EC%99%80%EC%9D%98-%EA%B4%80%EA%B3%84/

rowId 관련해서는 이 글 참고해주시면 될 것 같아요ㅎㅎ! 저희는 웬만하면 id와 rowid가 일치하도록 설정해뒀지만 id생성 시 어떤 에러가 날 지 모르니까요...!

2022-07-26 14:43 UTC, phj0407 commented on app/src/main/java/com/euphonyio/orderwith/data/dto/OrderMenu.kt
> +data class OrderMenu (
네, 가능은합니다만 굳이 복합키를 사용할 이유가 없다고 생각했습니다! 관계 테이블일 경우 PK를 단일키로 두는 게 일반적이기도 하구요.

https://sqlstudies.com/2016/08/29/natural-vs-artificial-primary-keys/
https://jwkim96.tistory.com/166 
https://stackoverflow.com/questions/2667988/why-single-primary-key-is-better-than-composite-keys

복합키 사용 시와 단일키 사용 시 장단점에  대해 자세히 나와있네요! 오랫동안 이야기된 주제지만 아직 뭐가 더 낫다고는 말 할 수 없고 상황에 따라 사용하는 듯 싶습니다! 저는 단일키 생성이 더 안전하며 용량이 작고, 저희 상황에서 사용 시 단점이 딱히 없다고 생각했는데, 혹시 복합키 사용을 추천하시는 이유가 따로 있으실까요?

2022-07-26 14:59 UTC, SeonJK approved these changes

2022-07-26 15:12 UTC, serim53 approved these changes

2022-07-26 15:13 UTC, merged